### ISSUE TITLE
Error msg preventing the script from working

### ISSUE THREAD

**Issue by dikodahan** [jupe76/bmwcdapi#4]
This is the error message I am getting in the openhab log:
```
2019-01-04 15:16:03.513 [INFO ] [ipse.smarthome.model.script.bmwcdapi] - forced connectedDrive API call
2019-01-04 15:16:03.674 [INFO ] [ipse.smarthome.model.script.bmwcdapi] - Traceback (most recent call last):
  File "/etc/openhab2/scripts/bmwcdapi.py", line 23, in <module>
    import requests
ImportError: No module named 'requests'
```
Trying to run the command manually with '-p' I am getting the following:
```
[15:20:32] openhabian@openHAB:/etc/openhab2$ sudo python scripts/bmwcdapi.py -p
[sudo] password for openhabian: 
Traceback (most recent call last):
  File "scripts/bmwcdapi.py", line 25, in <module>
    import urllib.parse
ImportError: No module named parse
```

Any thoughts what may be the reason.

**Comment by dikodahan** [comment]
This was a missing Python3 requirement. After installing it it is working now.
